---

- name: Installs Docker and Firewall
  hosts: all
  sudo: yes

  tasks:
    - stat: path=/sbin/insserv
      register: insserv_exists
    - name: Symlink insserv
      file: src=/usr/lib/insserv/insserv dest=/sbin/insserv state=link
      when: insserv_exists.stat.exists == False

    - apt: name=apt-transport-https
    - include: tasks/docker.yml

    - include: tasks/collectd.yml
      tags:
        - collectd

    - name: ng_key
      copy: >
        content="{{ ng_key }}"
        dest=/root/ng_key
      when: ng_key|default("") != ""
      tags:
        - git_key

    - name: ng_key.pub
      copy: >
        src=files/ng_key.pub
        dest=/root/ng_key.pub
      tags:
        - git_key

    - name: Permissions for ng_key
      file: >
        mode=0600
        path=/root/ng_key
      when: ng_key|default("") != ""
      tags:
        - git_key

    - include: tasks/newrelic.yml
      when: newrelic_license_key|default("") != ""
      tags:
        - newrelic
