---

- name: Update proxy
  git: >
    repo=git://github.com/castawaylabs/dproxy.js.git
    dest=/home/proxy
    accept_hostkey=True
  tags:
    - proxy_repo_update
    - repo_update

- name: Install credentials
  template: src=credentials.js dest=/home/proxy/lib/credentials.js

- name: Install SSL Certificate
  copy: content="{{ ngapp_io_crt }}" dest=/home/proxy/server.crt

- name: Install SSL Key
  copy: content="{{ ngapp_io_key }}" dest=/home/proxy/server.key

- name: Install SSL CA Chain
  copy: content="{{ ngapp_io_ca }}" dest=/home/proxy/server.ca

- name: Remove proxy
  docker: image="castawaylabs/node-docker" name="ng_proxy" state=absent

- name: Run NG-proxy
  docker: >
    image=castawaylabs/node-docker
    volumes="/home/proxy:/srv/app"
    name=ng_proxy
    env="NODE_ENV=production"
    ports="80:80,443:443"
    net=host
    state=running
