---

- name: Update proxy
  git: >
    repo="{{ apps.proxy.git_repo }}"
    dest="{{ apps.proxy.location }}"
    accept_hostkey=True
  when: apps.proxy.is_git == True
  tags:
    - proxy_repo_update
    - repo_update

- name: Install credentials
  template: >
    src=credentials.js
    dest="{{ apps.proxy.location }}/lib/credentials.js"

- include: ssl.yml
  when: apps.proxy.ssl == True

- name: Remove proxy
  docker: >
    image="{{registry}}castawaylabs/node-docker:latest"
    name=ng_proxy
    state=absent

- name: Run NG-proxy
  docker: >
    image="{{registry}}castawaylabs/node-docker:latest"
    volumes="{{ apps.proxy.location }}:/srv/app"
    name=ng_proxy
    env="{{ apps.proxy.env }}"
    ports="80:80,443:443"
    net=host
    state=started
    restart_policy=always
