---

- name: Update ng-backend
  git: repo=ssh://git@lab.castawaylabs.com/nodegear/ng-backend.git dest=/home/ng-backend key_file=/root/ng_key accept_hostkey=yes
- name: Install credentials
  template: src=templates/ng_backend.json dest=/home/ng-backend/lib/credentials.json
- name: Run NG-Backend
  docker: image="castawaylabs/node-docker" volumes="/home/ng-backend:/srv/app,/root/ng_key:/root/.ssh/id_rsa,/root/ng_key.pub:/root/.ssh/id_rsa.pub,/root/ng-backend/lib/scripts:/ng-scripts,/var/run/docker.sock:/var/run/docker.sock" name="ng_backend" env="NODE_ENV=production" state=running