---

- name: Update ng-backend
  git: >
    repo="{{ apps.backend.git_repo }}"
    dest="{{ apps.backend.location }}"
    key_file=/root/ng_key
    accept_hostkey=yes
    version="{{ apps.backend.version }}"
  when: apps.backend.is_git == True
  tags:
    - backend_repo_update
    - repo_update

- name: Install credentials
  template: >
    src=ng_backend.json
    dest="{{ apps.backend.location }}/configuration.json"

- stat: path=/usr/local/go/bin
  register: go_compiled

- name: Get Go
  get_url: url=https://storage.googleapis.com/golang/go1.4.2.linux-amd64.tar.gz dest=/tmp/go1.4.2.linux-amd64.tar.gz
  when: go_compiled.stat.exists == False

- name: Unpackage Go
  unarchive: src=/tmp/go1.4.2.linux-amd64.tar.gz dest=/usr/local copy=no
  when: go_compiled.stat.exists == False

- name: Install init script
  template: >
    src=initscript.bash
    dest=/etc/init.d/ng_backend
    group=root
    owner=root
    mode=0755

- name: Run NG-Backend
  service: >
    enabled=yes
    name=ng_backend
    state=restarted
