---

- name: Update NG-Frontend
  git: repo=ssh://git@lab.castawaylabs.com/nodegear/ng-frontend.git dest=/home/ng-frontend key_file=/root/ng_key accept_hostkey=yes

- name: Install credentials
  template: src=ng_frontend.json dest=/home/ng-frontend/lib/credentials.json

- name: Run NG-Frontend
  docker: image="castawaylabs/node-docker" volumes="/home/ng-frontend:/srv/app,/root/ng_key:/root/.ssh/id_rsa,/root/ng_key.pub:/root/.ssh/id_rsa.pub" ports="127.0.0.1:9000:80" name="ng_frontend" env="PORT=80,NODE_ENV=production" state=running

- name: Install NGINX
  include: nginx.yml