---

- name: Update fs
  git: >
    repo={{ apps.fs.git_repo }}
    dest={{ apps.fs.location }}
    accept_hostkey=yes
    version={{ apps.fs.version }}
  when: apps.fs.is_git == True
  tags:
    - fs_repo_update
    - repo_update

- name: Install credentials
  template: >
    src=credentials.json
    dest={{ apps.fs.location }}/lib/credentials.json

- name: Remove fs
  docker: >
    image="{{registry}}castawaylabs/node-docker:latest"
    name=fs
    state=absent

- name: Run fs
  docker: >
    image="{{registry}}castawaylabs/node-docker:latest"
    name=fs
    env={{ apps.fs.env }}
    ports="{{ apps.fs.ip }}:{{ apps.fs.port }}:80"
    state=running
    volumes="{{ apps.fs.location }}:/srv/app,{{ apps.fs.dir }}:/files"
