---

- name: Update ng-git
  git: >
    repo={{ apps.git.git_repo }}
    dest={{ apps.git.location }}
    key_file=/root/ng_key
    accept_hostkey=yes
    version={{ apps.git.version }}
  when: apps.git.is_git == True
  tags:
    - git_repo_update
    - repo_update

- name: Install credentials
  template: src=ng_git.json dest={{ apps.git.location }}/lib/credentials.json

- name: Remove NG-Git
  docker: >
    image="{{registry}}castawaylabs/node-docker:latest"
    name=ng_git
    state=absent

- name: Run NG-Git
  docker: >
    image="{{registry}}castawaylabs/node-docker:latest"
    volumes="{{ apps.git.location }}:/srv/app"
    net=host
    name=ng_git
    env="{{ apps.git.env }}"
    state=running
