---

- include: images.yml

- name: Install Redis
  include: redis.yml

- name: Set up Mongodb
  include: mongodb.yml

- name: Set up Client Mongodb
  include: mongodb_client.yml

- name: Set up MySQL
  include: mysql.yml

- name: Mongodb MMS Clients
  include: mongodb_backup.yml