---

# MMS Stuff

# Delete happens because sometimes ng_mongodb is removed, and then the link isn't reestablished

- name: Delete MMS Docker
  docker: >
    image="{{registry}}castawaylabs/mms-docker:latest"
    name="mms"
    state=absent

- name: Delete MMS Backup Docker
  docker: >
    image="{{registry}}castawaylabs/mms-backup-docker:latest"
    name="mms_backup"
    state=absent
  when: mms_key|default("") != ""

###
# MMS Monitoring

- name: Run MMS Docker
  docker: >
    image="{{registry}}castawaylabs/mms-docker:latest"
    name=mms
    env="MMS_KEY={{ mms_key }}"
    links="ng_mongodb:ng_mongodb,ng_client_mongodb:ng_client_mongodb"
    state=started
    restart_policy=always
  when: mms_key|default("") != ""

###
# MMS Backup

- name: Run MMS Backup Docker
  docker: >
    image="{{registry}}castawaylabs/mms-backup-docker:latest"
    name=mms_backup
    env="MMS_KEY={{ mms_key }}"
    links="ng_mongodb:ng_mongodb,ng_client_mongodb:ng_client_mongodb"
    state=started
    restart_policy=always
  when: mms_key|default("") != ""
